export const mockInventory = [
  {
    id: '1',
    name: '10µF Capacitor',
    partNumber: 'CAP-10UF-001',
    stock: 850,
    monthlyRequired: 1000,
    unit: 'pieces',
    category: 'Capacitors',
    supplier: 'ABC Electronics',
    location: 'Shelf A-1',
    lastUpdated: '2024-02-10',
    createdAt: '2024-01-15',
    reorderLevel: 200,
  },
  {
    id: '2',
    name: '100Ω Resistor',
    partNumber: 'RES-100-002',
    stock: 2500,
    monthlyRequired: 2000,
    unit: 'pieces',
    category: 'Resistors',
    supplier: 'XYZ Components',
    location: 'Shelf B-3',
    lastUpdated: '2024-02-12',
    createdAt: '2024-01-20',
    reorderLevel: 400,
  },
  {
    id: '3',
    name: 'ATmega328P Microcontroller',
    partNumber: 'MCU-ATM328-003',
    stock: 45,
    monthlyRequired: 500,
    unit: 'pieces',
    category: 'Microcontrollers',
    supplier: 'Tech Distributors',
    location: 'Shelf C-2',
    lastUpdated: '2024-02-13',
    createdAt: '2024-01-25',
    reorderLevel: 100,
  },
  {
    id: '4',
    name: 'LED Red 5mm',
    partNumber: 'LED-RED-5MM-004',
    stock: 1200,
    monthlyRequired: 800,
    unit: 'pieces',
    category: 'LEDs',
    supplier: 'Light Components Inc',
    location: 'Shelf D-1',
    lastUpdated: '2024-02-11',
    createdAt: '2024-01-18',
    reorderLevel: 160,
  },
  {
    id: '5',
    name: 'PCB FR4 Single Layer',
    partNumber: 'PCB-FR4-SL-005',
    stock: 150,
    monthlyRequired: 1500,
    unit: 'pieces',
    category: 'PCBs',
    supplier: 'Board Manufacturers Ltd',
    location: 'Shelf E-4',
    lastUpdated: '2024-02-09',
    createdAt: '2024-01-10',
    reorderLevel: 300,
  },
  {
    id: '6',
    name: '220µF Electrolytic Capacitor',
    partNumber: 'CAP-220UF-006',
    stock: 600,
    monthlyRequired: 600,
    unit: 'pieces',
    category: 'Capacitors',
    supplier: 'ABC Electronics',
    location: 'Shelf A-2',
    lastUpdated: '2024-02-14',
    createdAt: '2024-01-30',
    reorderLevel: 120,
  },
  {
    id: '7',
    name: '1kΩ Resistor',
    partNumber: 'RES-1K-007',
    stock: 3200,
    monthlyRequired: 1500,
    unit: 'pieces',
    category: 'Resistors',
    supplier: 'XYZ Components',
    location: 'Shelf B-4',
    lastUpdated: '2024-02-12',
    createdAt: '2024-01-22',
    reorderLevel: 300,
  },
  {
    id: '8',
    name: 'Crystal Oscillator 16MHz',
    partNumber: 'XTAL-16MHZ-008',
    stock: 80,
    monthlyRequired: 400,
    unit: 'pieces',
    category: 'Oscillators',
    supplier: 'Frequency Components',
    location: 'Shelf F-1',
    lastUpdated: '2024-02-10',
    createdAt: '2024-01-12',
    reorderLevel: 80,
  },
];

export const getInventoryStats = (inventory) => {
  const total = inventory.length;
  const lowStock = inventory.filter(item => 
    item.stock < (item.monthlyRequired * 0.2)
  ).length;
  const outOfStock = inventory.filter(item => item.stock === 0).length;
  
  return {
    total,
    lowStock,
    outOfStock,
    inStock: total - lowStock - outOfStock,
  };
};
